package com.f3rren.sentinel.attack.dataexposure;

import com.f3rren.sentinel.attack.AttackModule;
import com.f3rren.sentinel.http.HttpResponseData;
import com.f3rren.sentinel.http.SentinelHttpClient;
import com.f3rren.sentinel.model.Endpoint;
import com.f3rren.sentinel.model.EndpointParam;
import com.f3rren.sentinel.model.Finding;
import com.f3rren.sentinel.model.Severity;
import com.f3rren.sentinel.model.VulnerabilityType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.core.annotation.Order;
import org.springframework.http.HttpMethod;
import org.springframework.stereotype.Component;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;

/**
 * Flags a GET response whose body includes a field whose <em>name</em> suggests it holds
 * sensitive data - a credential, secret, or a personal/financial identifier - that generally has
 * no reason to ever be serialized back to a caller, regardless of who's asking. No fuzzing, no
 * identity required: like {@link com.f3rren.sentinel.attack.misconfig.SecurityMisconfigurationScanner},
 * this only inspects one legitimate GET's ordinary successful response per endpoint, recursively
 * (objects and arrays, up to a bounded depth) - so it runs safely, anonymously, and needs no
 * ordering relative to state-mutating checks.
 * <p>
 * Detection is a heuristic on a small, fixed set of field-name keywords, matched case- and
 * separator-insensitively (so {@code password}, {@code passwordHash}, and {@code user_password}
 * all match {@code password}) - not real insight into the target's data model. Kept deliberately
 * short and unambiguous (the same philosophy BFLA's path-keyword list follows) to limit false
 * positives: a generic word like "token" is deliberately excluded, since it also matches entirely
 * legitimate fields (a pagination cursor, a CSRF token issued to the caller) far more often than
 * an actual leak.
 * <p>
 * The matched field's actual value is never included in a finding's evidence - only its name and
 * JSON path - so a report generated by this module can't itself become a copy of the leaked data.
 */
@Component
@Order(5)
@ConditionalOnProperty(prefix = "sentinel.scan.data-exposure", name = "enabled", havingValue = "true", matchIfMissing = true)
public class DataExposureScanner implements AttackModule {

    private static final Logger log = LoggerFactory.getLogger(DataExposureScanner.class);

    private static final int MAX_JSON_SEARCH_DEPTH = 6;

    private static final Map<String, Severity> SENSITIVE_FIELD_KEYWORDS;

    static {
        Map<String, Severity> keywords = new LinkedHashMap<>();
        // Directly enables account takeover if leaked - CRITICAL.
        keywords.put("password", Severity.CRITICAL);
        keywords.put("secret", Severity.CRITICAL);
        keywords.put("privatekey", Severity.CRITICAL);
        // Severe privacy/financial impact, but doesn't by itself compromise the application - HIGH.
        keywords.put("ssn", Severity.HIGH);
        keywords.put("creditcard", Severity.HIGH);
        keywords.put("cardnumber", Severity.HIGH);
        keywords.put("cvv", Severity.HIGH);
        SENSITIVE_FIELD_KEYWORDS = Collections.unmodifiableMap(keywords);
    }

    private static final String RECOMMENDATION =
            "Exclude fields holding credentials, secrets, or other sensitive data from API "
            + "responses entirely - never serialize them, even to the resource's own owner. If "
            + "the caller only needs to know a value exists (not what it is), return a boolean "
            + "or a masked/partial representation instead of the real value.";

    private final SentinelHttpClient httpClient;
    private final ObjectMapper objectMapper = new ObjectMapper();

    public DataExposureScanner(SentinelHttpClient httpClient) {
        this.httpClient = httpClient;
    }

    @Override
    public String name() {
        return "data-exposure";
    }

    @Override
    public List<Finding> scan(Endpoint endpoint) {
        if (!HttpMethod.GET.equals(endpoint.method())) {
            return List.of();
        }

        Map<String, String> params = new LinkedHashMap<>();
        for (EndpointParam param : endpoint.params()) {
            params.put(param.name(), param.sampleValue());
        }

        HttpResponseData response;
        try {
            response = httpClient.exchange(endpoint.method(), endpoint.url(), params);
        } catch (Exception e) {
            log.warn("Data-exposure check failed for {} {}: {}", endpoint.method(), endpoint.url(), e.getMessage());
            return List.of();
        }

        if (response.statusCode() < 200 || response.statusCode() >= 300) {
            return List.of();
        }

        JsonNode root;
        try {
            root = objectMapper.readTree(response.bodyOrEmpty());
        } catch (Exception e) {
            return List.of();
        }

        List<SensitiveFieldMatch> matches = new ArrayList<>();
        findSensitiveFields(root, "", 0, matches);

        return matches.stream().map(match -> buildFinding(endpoint, match)).toList();
    }

    private void findSensitiveFields(JsonNode node, String path, int depth, List<SensitiveFieldMatch> matches) {
        if (node == null || depth > MAX_JSON_SEARCH_DEPTH) {
            return;
        }
        if (node.isObject()) {
            for (Map.Entry<String, JsonNode> entry : node.properties()) {
                String childPath = path.isEmpty() ? entry.getKey() : path + "." + entry.getKey();
                matchedKeyword(entry.getKey())
                        .ifPresent(keyword -> matches.add(new SensitiveFieldMatch(childPath, keyword)));
                findSensitiveFields(entry.getValue(), childPath, depth + 1, matches);
            }
        } else if (node.isArray()) {
            int index = 0;
            for (JsonNode element : node) {
                findSensitiveFields(element, path + "[" + index + "]", depth + 1, matches);
                index++;
            }
        }
    }

    /**
     * Case- and separator-insensitive: strips everything but letters/digits before comparing, so
     * {@code user_password}, {@code UserPassword}, and {@code PASSWORD} all match {@code password}.
     */
    private Optional<String> matchedKeyword(String fieldName) {
        String normalized = fieldName.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]", "");
        for (String keyword : SENSITIVE_FIELD_KEYWORDS.keySet()) {
            if (normalized.contains(keyword)) {
                return Optional.of(keyword);
            }
        }
        return Optional.empty();
    }

    private Finding buildFinding(Endpoint endpoint, SensitiveFieldMatch match) {
        Severity severity = SENSITIVE_FIELD_KEYWORDS.get(match.keyword());
        return new Finding(
                UUID.randomUUID().toString(),
                name(),
                VulnerabilityType.EXCESSIVE_DATA_EXPOSURE,
                severity,
                endpoint.url(),
                endpoint.method().name(),
                match.jsonPath(),
                "",
                "The response includes a field whose name suggests it holds sensitive data (a "
                        + "credential, secret, or personal/financial identifier) that shouldn't be "
                        + "returned to the client.",
                "Field at JSON path '" + match.jsonPath() + "' (matched keyword '" + match.keyword()
                        + "') found in the response to " + endpoint.method() + " " + endpoint.url()
                        + " - the value itself is not included in this report.",
                RECOMMENDATION
        );
    }

    private record SensitiveFieldMatch(String jsonPath, String keyword) {
    }
}
